# Generated by Django 2.2 on 2020-01-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_notificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(default='demo@organization.supply', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
