# Generated by Django 2.2.9 on 2020-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organization", "0011_auto_20200212_2122")]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.ImageField(
                default="organization/location/default.png",
                upload_to="organization/location/",
            ),
        )
    ]
