# Generated by Django 2.2.9 on 2020-02-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20200224_2020'),
        ('organization', '0012_auto_20200224_2010'),
    ]

    operations = [
    ]
