# Generated by Django 2.2.9 on 2020-04-12 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20200322_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='adapter_auth',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='adapter_service_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='adapter_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
