# Generated by Django 2.2.13 on 2021-02-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20200322_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
