# Generated by Django 2.2.9 on 2020-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20200412_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_service_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
