# Generated by Django 2.2.5 on 2019-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0002_auto_20190926_2017")]

    operations = [
        migrations.AddField(
            model_name="location", name="desc", field=models.TextField(default="")
        ),
        migrations.AddField(
            model_name="mutation", name="desc", field=models.TextField(default="")
        ),
        migrations.AddField(
            model_name="product", name="desc", field=models.TextField(default="")
        ),
    ]
