# Generated by Django 2.2 on 2020-01-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [migrations.DeleteModel(name="NotificationSubscription")]
