# Generated by Django 2.2.6 on 2019-10-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0002_auto_20191024_2046")]

    operations = [migrations.DeleteModel(name="UserProfile")]
