# Generated by Django 2.2.6 on 2019-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/profile/default.png', upload_to='user/profile/'),
        ),
    ]
